# =====================================================
# Eureka Client
# =====================================================
#spring.application.name=Config-Default
# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Register this service with Eureka
eureka.client.register-with-eureka=true

# Fetch registry information from Eureka
eureka.client.fetch-registry=true

# Prefer IP address instead of hostname
eureka.instance.prefer-ip-address=true
